### PR TITLE
tsx version

### PR DESCRIPTION
**Pull request by nicitaacom**
## Please describe your changes

[add a description of your changes here]

## How did you accomplish your changes

[add a detailed description of how you accomplished your changes here]

## How have you tested your changes

[add a detailed description of how you tested your changes here]

## How can we verify your changes

[add a detailed description of how we can verify your changes here]

## Remarks

[add any additional remarks here]

## Checklist

- [ ] The changes are not breaking the editor
- [ ] Added tests where possible
- [ ] Followed the guidelines
- [ ] Fixed linting issues

## Related issues

[add a link to the related issues here]

### CODE REVIEW

**Comment by bdbch** [comment]
Could you please explain what you are trying to solve with this PR or what kind of demo this is?

**Comment by nicitaacom** [comment]
> Could you please explain what you are trying to solve with this PR or what kind of demo this is?

https://tiptap.dev/docs/editor/examples/suggestions
I see js here
I'm using TypeScript
So it would be nice if I would see TypeScript version there

**Comment by bdbch** [comment]
I see. For our demos though we would like to stick to Javascript as it is easier to understand for more people. Typescript developers should be fine understanding Vanilla Javascript & Javascript devs should be able to also understand our examples without learning Typescript first. Thanks for your PR though!

**Comment by nicitaacom** [comment]
> Typescript developers should be fine understanding Vanilla Javascript

That's right

I don't understand which type editor has
Also this is some uncommon type for clientRect

```ts
interface SuggestionProps {
  query: string;
  editor: any;
  clientRect?: (() => DOMRect | null) | null | undefined;
}
```

**Comment by bdbch** [comment]
editor here can either be the type `Editor` of the core package or from one of the library packages. Could improve typings there.

The clientRect type is that way because it's the callback function that is required for the tippyjs props.

**Pull request closed without merging**
