### PR TITLE
fix: streamline html package generation functions to work as expected

### LINKED ISSUE #4089: [Bug]: Cannot parse generated html from YouTube extension
### Which packages did you experience the bug in?

extension-youtube, html

### What Tiptap version are you using?

^2.0.0

### What’s the bug you are facing?

Using `generateHTML` & `generateJSON` utilities from `@tiptap/html` doesn't work with the YouTube extension. Sample easily replicable test case:

```ts
import { generateJSON, generateHTML } from '@tiptap/html';
import Document from '@tiptap/extension-document';
import Text from '@tiptap/extension-text';

it('can convert from & to html', async () => {
    const extensions = [Document, Text, Youtube];
    const html = `<p>Tiptap now supports YouTube embeds! Awesome!</p>
      <div data-youtube-video>
        <iframe src="https://www.youtube.com/watch?v=cqHqLQgVCgY"></iframe>
      </div>`;
    const json = generateJSON(html, extensions);
    expect(generateHTML(json, extensions)).to.equal(html);
});
```

Test fails with:
```
Unknown CSS selector type descendant div[data-youtube-video] iframe [
  { type: 'tag', name: 'div', namespace: null },
  {
    type: 'attribute',
    name: 'data-youtube-video',
    action: 'exists',
    value: '',
    namespace: null,
    ignoreCase: null
  },
  { type: 'descendant' },
  { type: 'tag', name: 'iframe', namespace: null }
]

TypeError: Cannot read properties of null (reading 'includes')
❯ getEmbedUrlFromYoutubeUrl ../../node_modules/@tiptap/extension-youtube/src/utils.ts:56:11
❯ Object.renderHTML ../../node_modules/@tiptap/extension-youtube/src/youtube.ts:138:22
❯ Object.schema.toDOM [as youtube] ../../node_modules/@tiptap/core/src/helpers/getSchemaByResolvedExtensions.ts:100:32
❯ DOMSerializer.serializeNodeInner ../../node_modules/prosemirror-model/dist/index.js:3280:100
❯ ../../node_modules/prosemirror-model/dist/index.js:3272:34
❯ Fragment.forEach ../../node_modules/prosemirror-model/dist/index.js:255:13
❯ DOMSerializer.serializeFragment ../../node_modules/prosemirror-model/dist/index.js:3246:18
❯ getHTMLFromFragment ../../node_modules/@tiptap/html/src/getHTMLFromFragment.ts:5:53
❯ Module.generateHTML ../../node_modules/@tiptap/html/src/generateHTML.ts:10:10
❯ src/index.spec.ts:47:12
```

### What browser are you using?

Chrome

### Code example

_No response_

### What did you expect to happen?

I would expect the above test to pass.

### Anything to add? (optional)

Looks like this could be an issue with `zeed-dom` and how it parses the html. I would happily open an issue there however since I couldn't find much information relating to a similar issue (only [this](https://github.com/ueberdosis/tiptap/issues/3539) seems close) it's hard to tell exactly what the issue is.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

### PR DESCRIPTION
**Pull request by bdbch**
## Changes Overview
This PR removes logic that was specific to the `@tiptap/html` package and didn't work the same way the core `generateHTML` and `generateJSON` functions work. This caused issues with a few extensions (for example the Youtube extension not being able to be generated back to HTML from JSON, see #4089)

I kept the original HTML `getJSON` and `getHTML` functions to not break existing code for users but maybe we should add a deprecation message to it?

## Implementation Approach
I removed the logic of the functions of the html package and just used a reference to the core packages util functions.

## Testing Done
I tried running JSON and HTML generation steps before and after and checked if unexpected things were happening or the output was false.

## Verification Steps
1. Try to check out this PR
2. Create a demo and simply run the code example below
3. Verify output

```js
import { generateJSON, generateHTML } from '@tiptap/html'
const extensions = [Document, Paragraph, Text, Youtube]
const content `<p>Hello</p><div data-youtube-video><iframe src="..."></iframe></div>`

const json = generateJSON(content, extensions)
const html = generateHTML(json, extensions)

console.log(json, html)
```

## Checklist
- [x] I have renamed my PR according to the naming conventions. (e.g. `feat: Implement new feature` or `chore(deps): Update dependencies`)
- [x] My changes do not break the library.
- [x] I have added tests where applicable.
- [x] I have followed the project guidelines.
- [x] I have fixed any lint issues.

## Related Issues
- fixes #4089

### CODE REVIEW

**Comment by nperez0111** [comment]
Wouldn't this break being able to use `@tiptap/html` package on the server-side where this is no reference to a global document object 🤔

**Comment by bdbch** [comment]
True, didn't think about this. I'll add back the zeed fallback if the document is not available but I guess this will also cause the issues from #4089 to pop back up.

**Comment by nperez0111** [comment]
If you are on the server side anyway I think that we could use another package than zeed-dom. Perhaps happy-dom? It is a heavier package, but we should not be using this package in the browser. We could even give a warning to a user if in development mode and there is a global document object that they should not be bundling this into their application.

**Comment by bdbch** [comment]
Closing this for now as we'd probably do this via another html parser.

**Pull request closed without merging**
