### PR TITLE
fix can not copy content of new inserted mention

### PR DESCRIPTION
**Pull request by Priestch**

### CODE REVIEW

**Comment by hanspagel** [comment]
Thanks for the follow up PR, great work!

It changes the behaviour of `replaceText` and would break the app for people using it already. Any idea how to fix that without a breaking change? If not, no worries, I can have a look next week.

**Comment by Priestch** [comment]
@hanspagel Maybe add another default parameter for the `replaceText` function, and create node content with attrs and the new added argument when called.

**Comment by hanspagel** [comment]
Sounds good!

**Comment by Priestch** [comment]
@hanspagel I will send another pr later.

**Comment by Priestch** [comment]
@hanspagel I pushed a new commit to fix the compatible problem.

**Comment by USasikumar** [comment]
@Priestch Which version is the issue of mentioning multiple mentions in the same paragraph fixed? I have installed tiptap through npm install 

This is my current tiptap version

 **"tiptap": "^1.30.0",
 "tiptap-extensions": "^1.33.2",**

please tell me how to fix the issue

**Comment by Priestch** [comment]
@USasikumar This pr is still open, so the multiple mentions problem still there, but you can have a look the last commit above.

**Comment by USasikumar** [comment]
> @USasikumar This pr is still open, so the multiple mentions problem still there, but you can have a look the last commit above.

@hanspagel  can you review and push the lastest commit if it solves the multiple mentions in the same paragraph issue

**Comment by andreasvirkus** [comment]
@hanspagel could you take a look whenever possible? 🙏

**Comment by hanspagel** [comment]
Thanks for the work on this and the mention here! Sorry for the long wait. Life hit me and I hope to be able to look at it in the first week of January. 😏 It’s #1 on my list for the new year.

**Comment by USasikumar** [comment]
> Thanks for the work on this and the mention here! Sorry for the long wait. Life hit me and I hope to be able to look at it in the first week of January.  It’s #1 on my list for the new year.

@hanspagel 
Please look into this on priority my entire application is stuck because of this issue. We are critically behind client deadlines.

**Comment by andreasvirkus** [comment]
@USasikumar you can create a local workaround with custom extensions until this is resolved. See https://github.com/ueberdosis/tiptap/issues/874#issuecomment-742236801

**Comment by hanspagel** [comment]
Thanks @Priestch! Looks pretty good to me. :) I start to prepare the next release and merge it. 

Recent releases introduced too many bugs (like this one here), so I’ll take some time before publishing, but expect it in the first two weeks of January.

And thanks to all others helping out here and in the issues, great work! 👏

**Pull request merged**
