### PR TITLE
Docs/installation cdn

### PR DESCRIPTION
**Pull request by RicoTrevisan**
## Please describe your changes

- Added 2 CDN examples: esm.sh, esm.run.
- Uncommented CDN from the installation main page so that users can access it.

## How did you accomplish your changes

I've built examples of each one of them in Codepen:
- esm.sh: https://codepen.io/ricotrevisan/pen/YzjqWBJ
- esm.run: https://codepen.io/ricotrevisan/pen/MWPByaq

## How have you tested your changes

With the Codepen examples.

## How can we verify your changes

Just open the links to the different Codepens to make sure they work.

## Remarks

I'm a rookie contributor, I'm trying to learn, but not sure if I'm doing it correctly. If something is missing or unclear, please let me know -- I'd love to learn.

## Checklist

- [x] The changes are not breaking the editor
- [x] Added tests where possible
- [x] Followed the guidelines
- [x] Fixed linting issues

## Related issues

[add a link to the related issues here]

### CODE REVIEW

**Comment by svenadlung** [comment]
@RicoTrevisan Thank you so much for your contribution.

The ESM.RUN sandbox seems to have error I think. It shows 
`caught RangeError: Adding different instances of a keyed plugin (plugin$1)`

I am wondering how they handle peer dependencies like `@tiptap/pm`.

**Comment by RicoTrevisan** [comment]
Hey @svenadlung , thanks for catching that. I've tried to get to the root-cause of that issue, but failed. Let's leave just the esm.sh implementation there. Hopefully this can be of help to someone.

Thanks for letting me contribute.

**Review by ije — APPROVED** [review]
LGTM

**Comment by ije** [comment]
hi, i am the maintainer of esm.sh, glad to see this PR. if you have any problem with esm.sh please just tell me, i am happy to fix/improve. thanks!

**Review by bdbch — APPROVED** [review]

**Pull request merged**
