### PR TITLE
Use correct CSS name for attribute

### PR DESCRIPTION
**Pull request by Flamenco**

### CODE REVIEW

**Comment by Flamenco** [comment]
2 different files, one vue one react

**Comment by Flamenco** [comment]
You can squash em if thats your fancy.

**Comment by philippkuehn** [comment]
Hey, there is both `.hljs-attribute` and `.hljs-attr` but in this case it’s intended that `.hljs-attr` has no styling.

**Comment by Flamenco** [comment]
No styling is still the wrong tag...  I found the error because I used the template as the foundation for a project.

**Comment by Flamenco** [comment]
I also left the old tag as to not break existing code.

**Comment by philippkuehn** [comment]
These are two different things. `hljs-attr` is for XML attributes and `hljs-attribute` is for object attributes.

The current theme matches our documentation style but feel free to use any of the prebuild [highlight.js themes](https://github.com/highlightjs/highlight.js/tree/main/src/styles) or a custom one.

**Comment by Flamenco** [comment]
Ah, that is good to know! Ty.

**Pull request closed without merging**
