### PR TITLE
Fix: configured/extended extensions should keep their original config

### PR DESCRIPTION
**Pull request by tleruitte**
## Please describe your changes

Extensions, marks and nodes should keep their original config when they are extended or configured. 

## How did you accomplish your changes

n/a.

## How have you tested your changes

Tested locally.

## How can we verify your changes

```
import Code from '@tiptap/extension-code'
import Document from '@tiptap/extension-document'
import Paragraph from '@tiptap/extension-paragraph'
import Text from '@tiptap/extension-text'
import { EditorContent, useEditor } from '@tiptap/react'
import React from 'react'

export default () => {
  const editor = useEditor({
    extensions: [Document, Paragraph, Text, Code.configure({
      HTMLAttributes: {
        class: 'my-custom-class',
      },
    })],
    content: `
        <p>This isn’t code.</p>
        <p><code>This is code.</code></p>
      `,
  })

  if (!editor) {
    return null
  }

  return (
    <>
      <button
        onClick={() => editor.chain().focus().toggleCode().run()}
        className={editor.isActive('code') ? 'is-active' : ''}
      >
        toggleCode
      </button>
      <button
        onClick={() => editor.chain().focus().setCode().run()}
        disabled={editor.isActive('code')}
      >
        setCode
      </button>
      <button
        onClick={() => editor.chain().focus().unsetCode().run()}
        disabled={!editor.isActive('code')}
      >
        unsetCode
      </button>

      <EditorContent editor={editor} />
    </>
  )
}
```

Before this fix, the instance of `Code` doesn't have `excludes`, `code` or `exitable` set. This prevents the right arrow keyboard shortcut to exit the code mark for instance. After the fix, the config is correctly extended and the new instance of `Code` uses the correct values for `excludes`, `code` or `exitable`. Same goes for `Extension` and `Node`. 

## Remarks

This is especially noticeable when users use the StarterKit. StarterKit configures all extensions with `undefined` by default, which strips them all from their default config. 

## Checklist

- [ ] The changes are not breaking the editor
- [ ] Added tests where possible
- [ ] Followed the guidelines
- [ ] Fixed linting issues

## Related issues

I haven't filed an issue.

### CODE REVIEW

**Review by bdbch — APPROVED** [review]
LGTM - this does not break any functionality while you tested it? @tleruitte

CC @svenadlung - you want to take another look?

**Comment by tleruitte** [comment]
@bdbch Sorry I missed your comment. No, I didn't see any broken functionality with this fix!

**Review by svenadlung — APPROVED** [review]

**Comment by rfgamaral** [comment]
I'm wondering if this could be something released as `v2.1.7` 🤔😁

**Comment by tleruitte** [comment]
I think this got fixed in 2.1.0 by another pull request. https://github.com/ueberdosis/tiptap/releases/tag/v2.1.0

**Comment by tleruitte** [comment]
Never mind, just tested `2.1.11` and the bug is still present. https://github.com/ueberdosis/tiptap/pull/3822 only fix `configure`, but not `extend`. So I think we stil should merge this pull request. Let me know if/how I can help to get this merged.

**Comment by bdbch** [comment]
Sure thing, thanks for letting us know. @svenadlung do you have some time to check this PR?

**Comment by bdbch** [comment]
I merged it for now and will release a new RC version with this tomorrow. Would be nice if someone could check it out by then

**Comment by romansp** [comment]
This appears as fixed in `2.2.0-rc.4`.

Any idea why `exitable` is checked on `config` directly and not via `getExtensionField` helper? Though it doesn't seem to be necessary anymore because extension config is preserved now.
https://github.com/ueberdosis/tiptap/blob/42039c05f0894a2730a7b8f1b943ddb22d52a824/packages/core/src/ExtensionManager.ts#L240-L242

Also maybe `exitable` should be copied here?
https://github.com/ueberdosis/tiptap/blob/42039c05f0894a2730a7b8f1b943ddb22d52a824/packages/core/src/helpers/getSchemaByResolvedExtensions.ts#L145-L163

**Comment by Slapbox** [comment]
This commit causes #4617. See review comments.

**Pull request merged**
