### PR TITLE
fix emptyTextBlock detection to handle leaf nodes too

### LINKED ISSUE #4327: [Bug]: `renderText` does not propagate to `NodeSpec.leafText` and `extension-floating-menu` uses `Node.textContent` which uses `NodeSpec.leafText`
### Which packages did you experience the bug in?

core, extension-floating-menu

### What Tiptap version are you using?

2.0.4

### What’s the bug you are facing?

1.  Open a new empty paragraph, see the "FLOATING MENU".
2. Click "Insert foo".
3. The "FLOATING MENU" still shows! Even though the paragraph is not empty!

### What browser are you using?

Chrome

### Code example

https://codesandbox.io/p/sandbox/tiptap-leaftext-issue-skv4vm?file=%2Fsrc%2Fcomponents%2FEditor.vue%3A4%2C1

### What did you expect to happen?

The "FLOATING MENU" should not show on a non empty paragraph.

### Anything to add? (optional)

This is caused by:
https://github.com/ueberdosis/tiptap/blob/f387ad3dd4c2b30eaea33fb0ba0b42e0cd39263b/packages/extension-floating-menu/src/floating-menu-plugin.ts#L38-L55

It uses `Node.textContent` which uses `NodeSpec.leafText` to fill it. But Tiptap does not fill `NodeSpec.leafText` using Tiptap's `Node.renderText`, rather Tiptap has its own separate mechanism to generate text content from Nodes that doesn't integrate with ProseMirror's one (Maybe ProseMirror's one didn't exist at the time?). 

It does hook that implementation into ProseMirror text copy paste using [packages/core/src/extensions/clipboardTextSerializer.ts](https://github.com/ueberdosis/tiptap/blob/243bdb8c3f8f3497fa3e70cc49040894c44870f0/packages/core/src/extensions/clipboardTextSerializer.ts#L33-L34), but not into the Tiptap's own floating menu. Though maybe a simpler check can be done in the floating menu anyhow to check if the paragraph is empty or not.

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

### PR DESCRIPTION
**Pull request by bdbch**
## Changes Overview

This pull request includes a small but significant change to the `FloatingMenuView` class in the `packages/extension-floating-menu/src/floating-menu-plugin.ts` file. The change ensures that the `isEmptyTextBlock` condition also checks if the parent node has no children (`childCount === 0`).

This fixes a bug (see #4327) causing leaf nodes not to be counted as content of a node. It also deprecates the PR #4444

Changes in `FloatingMenuView`:

* Updated the `isEmptyTextBlock` condition to include a check for `childCount === 0` to ensure the block is truly empty.

## Checklist
- [x] I have created a [changeset](https://github.com/changesets/changesets) for this PR if necessary.
- [x] My changes do not break the library.
- [x] I have added tests where applicable.
- [x] I have followed the project guidelines.
- [x] I have fixed any lint issues.

## Related Issues
- Closes #4327

### CODE REVIEW

**Comment by nperez0111** [comment]
I wonder if this fix is still valid https://github.com/ueberdosis/tiptap/pull/4444

**Comment by bdbch** [comment]
Do we need to be that specific in that case though? I thought about it and I couldn't find a reason why a node should be considered empty even when it has any child nodes.

**Comment by nperez0111** [comment]
> Do we need to be that specific in that case though? I thought about it and I couldn't find a reason why a node should be considered empty even when it has any child nodes. Do you have any thing in mind that would cause a node to have child content but still should be considered empty for the floating menu?

I think you understood me reverse, if a node is something that can serialize to text (e.g. a mention), which has no child nodes, then to the floating menu it will be considered empy.

I did this in the current version to show what I mean
image


You can apply this diff in your project to see if your fix addresses this too, but I'm pretty sure the other fix addresses this:

```diff
diff --git a/demos/src/Nodes/Mention/React/index.jsx b/demos/src/Nodes/Mention/React/index.jsx
index 8d40a8d4d..ef78a95b6 100644
--- a/demos/src/Nodes/Mention/React/index.jsx
+++ b/demos/src/Nodes/Mention/React/index.jsx
@@ -4,7 +4,7 @@ import Document from '@tiptap/extension-document'
 import Mention from '@tiptap/extension-mention'
 import Paragraph from '@tiptap/extension-paragraph'
 import Text from '@tiptap/extension-text'
-import { EditorContent, useEditor } from '@tiptap/react'
+import { EditorContent, FloatingMenu, useEditor } from '@tiptap/react'
 import React from 'react'
 
 import suggestion from './suggestion.js'
@@ -35,5 +35,28 @@ export default () => {
     return null
   }
 
-  return <EditorContent editor={editor} />
+  return <div>
+  {editor && <FloatingMenu editor={editor} tippyOptions={{ duration: 100 }}>
+    <div className="floating-menu">
+      <button
+        onClick={() => editor.chain().focus().toggleHeading({ level: 1 }).run()}
+        className={editor.isActive('heading', { level: 1 }) ? 'is-active' : ''}
+      >
+        H1
+      </button>
+      <button
+        onClick={() => editor.chain().focus().toggleHeading({ level: 2 }).run()}
+        className={editor.isActive('heading', { level: 2 }) ? 'is-active' : ''}
+      >
+        H2
+      </button>
+      <button
+        onClick={() => editor.chain().focus().toggleBulletList().run()}
+        className={editor.isActive('bulletList') ? 'is-active' : ''}
+      >
+        Bullet list
+      </button>
+    </div>
+  </FloatingMenu>}
+  <EditorContent editor={editor} /></div>
 }
```

**Comment by nperez0111** [comment]
If yours works, then I'd go with the simpler one which is yours

**Pull request merged**
