### PR TITLE
Text Align Extension: issue with DOM update when multiple types exist and not every exist at the DOM of the editor.

### PR DESCRIPTION
**Pull request by echatzief**
…

## Please describe your changes

I have changed the `setTextAlign` and `unsetTextAlign` because if you used multiple types lets say ['heading', 'paragraph'] and at the DOM of the editor we only have a paragraph only no heading. Then when we call `setTextAlign` then it will go the the every loop and at the first try to updateAttributes for heading it will fail and it will stop there an the paragraph won't update because that how the every loop works. It stops on the first falsy value. Same happens for the `unsetTextAlign` function

## How did you accomplish your changes

I changed the setTextAlign and unsetTextAlign to use a map to go through every update and then validate the updates. That how we avoid the bug described above

## How have you tested your changes

Yes. I have tested locally with a Vue3 project

## How can we verify your changes

Try the scenario that we described.

## Checklist

- [X] The changes are not breaking the editor
- [ ] Added tests where possible
- [X] Followed the guidelines
- [X] Fixed linting issues

### CODE REVIEW

**Review by nperez0111 — APPROVED** [review]
This looks right to me

**Comment by bdbch** [comment]
Nice change. LGTM!

**Review by bdbch — APPROVED** [review]

**Comment by echatzief** [comment]
If it looks good then merge it 😀

**Comment by bdbch** [comment]
@echatzief sometimes we wait for another maintainer to also take a look

**Pull request merged**
