### PR TITLE
Fix example with placeholder

### PR DESCRIPTION
**Pull request by DannyFeliz**

### CODE REVIEW

**Comment by hanspagel** [comment]
What issue does this solve?

**Comment by DannyFeliz** [comment]
@hanspagel In the usage you don't necessary show how to use the placeholder in the template https://www.tiptap.dev/api/extensions/placeholder/#usage

**Comment by philippkuehn** [comment]
This is not how the placeholder extension works.

**Comment by goamn** [comment]
Then how is it supposed to be used? The example is very unclear. It looks like we can add a string into the css rule to make it change. But how do we change it via JS ... via the settings "placeholder" value?

**Comment by DannyFeliz** [comment]
@philippkuehn so, how do you use this extension then? I couldn't understand by only reading the documentation; that's why I created the PR

**Comment by goamn** [comment]
@DannyFeliz I have figured it out. The css rule is necessary. To change the placeholder it will be like this:
```
const editor = useEditor({
    extensions: [
      Placeholder.configure({
        placeholder: 'Enter some details here...',
      }),
      StarterKit,
    ],
  });
```
Also regarding the CSS rule, you can remove it on focus by adding ":not(:focus)" to the rule:
```
.ProseMirror:not(:focus) p.is-editor-empty:first-child::before {
  content: attr(data-placeholder);
  float: left;
  color: #ced4da;
  pointer-events: none;
  height: 0;
}
```

**Comment by DannyFeliz** [comment]
I see, thanks

**Comment by philippkuehn** [comment]
dynamic placeholders are also possible: https://github.com/ueberdosis/tiptap/issues/1292#issuecomment-867557863

**Comment by goamn** [comment]
Thanks @philippkuehn . Would be nice to have this part in the docs: `Placeholder.configure({placeholder: 'xyz'})`

**Pull request closed without merging**
