### PR TITLE
Vue 3 Perf updates

### LINKED ISSUE #4870: [Bug]: shouldShow broken in BubbleMenu extension from Vue 3 package
### Which packages did you experience the bug in?

core, pm, starter-kit, vue-3

### What Tiptap version are you using?

2.2.2

### What’s the bug you are facing?

I'm noticing that the `shouldShow` callback is not functioning as expected in the Vue implementation of the Bubble Menu. When using `editor.isActive` as part of the condition, the value returned from `isActive` doesn't represent that state that I expect.

### What browser are you using?

Chrome

### Code example

https://stackblitz.com/edit/vitejs-vite-kgmrcn?file=src%2Fcomponents%2FTiptap.vue,package.json

### What did you expect to happen?

Consider `shouldShow: ({ editor }) => editor.isActive('bold')`. I expect on first click into a bolded word that the bubble menu would become visible. However, it isn't and logging out the value of `isActive` in the method at that point returns `false`. But upon clicking again on any text (bold or not), the value then returns `true`. It's as if the `editor` state inside the callback is from before the click is registered.

### Anything to add? (optional)

I do not see this same behavior in the vanilla JS implementation of Bubble Menu. I have not tested any other frameworks.

For comparison to the code example below, here is a working vanilla JS port of the same code.
[https://stackblitz.com/edit/vitejs-vite-djsnpl?file=index.html,main.js&terminal=dev](https://stackblitz.com/edit/vitejs-vite-djsnpl?file=index.html,main.js&terminal=dev)

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [ ] Yes, I’m a sponsor. 💖

### PR DESCRIPTION
**Pull request by nperez0111**
- **revert: "revert: "fix(vue-3): fix editor.state updating too late during a transaction due to reactiveState fixes #4870 (#5252)""**
- **revert: "revert: "fix(vue-3): faster component rendering (#5206)""**
- **fix: backwards compatibility ref exposed methods**
- **fix(vue-3): provide app global (#5354)**
- **fix(vue-3): fix(vue-3): vue's VueNodeViewRenderer should return `null` for `contentDOM` (#3966)**

## Checklist
- [ ] I have created a [changeset](https://github.com/changesets/changesets) for this PR if necessary.
- [ ] My changes do not break the library.
- [ ] I have added tests where applicable.
- [ ] I have followed the project guidelines.
- [ ] I have fixed any lint issues.

### CODE REVIEW

**Comment by nperez0111** [comment]
Hi @Rirax, So I looked into this further, and found a bug with this implementation that I can't quite figure out how to resolve & I hope you would.

If you go to [this mention preview](https://deploy-preview-5373--tiptap-embed.netlify.app/src/nodes/mention/vue/) and try to add a mention with `@` and then use the arrow down key to move the selection down the list, the selection is not handled and instead the selection is moved within the editor when the custom vue component is supposed to be handling it: https://github.com/ueberdosis/tiptap/blob/aba6657d7026cf59a41b9532b767c8e3058b1b03/demos/src/Nodes/Mention/Vue/MentionList.vue#L46-L63

I did a git bisect & the first commit that had an issue was: 6ad77da961a9307cf8fc1bca3f67a285e78a9a19 which is regarding this PR https://github.com/ueberdosis/tiptap/pull/5206 that you made.

So for now I can't merge this as it is a regression in functionality.

I would very much appreciate your help here as I'm not seeing anything obvious for why events would not be handled by vue-3 properly here. Thanks for your contribution and support in this matter.

**Comment by nperez0111** [comment]
@Rirax  I was able to resolve this by exposing the proxy instead, is this correct? I'm unfamiliar with vue 3, much less it's internals: https://github.com/ueberdosis/tiptap/pull/5373/commits/960236855a01a52189dc65539103e8965381cef4

**Comment by Rirax** [comment]
Hi @nperez0111 ,
Thank you for your message.

I did my tests in vue-3 `Composition API` [where it is necessary to expose the methods you want to make public](https://vuejs.org/api/sfc-script-setup.html#defineexpose).

In the shared example it's vue-3 `Option API` and so `exposed` doesn't exist.

I've just tested in my case (Composition API),`this.renderedComponent.vNode?.component?.proxy` doesn't do the trick

**Comment by Rirax** [comment]
@nperez0111 

In my case `renderedComponent.vNode.component.proxy` exists but doesn't contain the required methods.

That way it works for me:
`  get ref() {
    // Composition API
    if (this.renderedComponent.vNode.component.exposed) {
      return this.renderedComponent.vNode.component.exposed;
    }

    // Option API
    return this.renderedComponent.vNode.component.proxy;
  }`

**Pull request merged**
