### PR TITLE
Feature/delete content when drop on another editor

### PR DESCRIPTION
**Pull request by LuchoCateura**
Now it works for Firefox too

### CODE REVIEW

**Comment by songispm** [comment]
Great !!!

Need you now. @bdbch

**Comment by bdbch** [comment]
Not yet. I'll see that we get it into the new release candidate for 2.1.0 soon. Should be coming in the next 2 days.

**Review by songispm — COMMENTED** [review]
Code Review:

image

The className is not correct now (in The latest version of the Tiptap), now is "tiptap ProseMirror".

Please change it before Merge, Or use `if (event.target.parentElement?.classList.contains('ProseMirror')){}`

By the way, really need this feature. Hope it can be released as soon as possible.

@bdbch @LuchoCateura

**Comment by songispm** [comment]
I tried a new plan. Please check this pull request and help test it. @bdbch @LuchoCateura 

[https://github.com/ueberdosis/tiptap/pull/4328](https://github.com/ueberdosis/tiptap/pull/4328)

https://github.com/ueberdosis/tiptap/assets/38745323/d9e6c03a-edb4-4543-b723-b7511c3a844c

**Comment by bdbch** [comment]
Closing this as #5893 implemented this fix.

**Pull request closed without merging**
