### PR TITLE
fix: #5851 - While setting content directly while using CharacterCount with limit is not obeyed

### LINKED ISSUE #5851: [Bug]: While setting `content` directly while using CharacterCount with limit is not obeyed
### Affected Packages

core,extension-character-count,react

### Version(s)

2.10.x

### Bug Description

I thought I messed up something, my editor was not recognizing the content, it was just white screen. After investigating I found out that, I was using `CharacterCount` extension with limit set to `1000`, my content length was longer than that.

- Can we have a console warning or something to solve the above nightmare for future users ?

Now there's another bug that I found is, my setup use the below way to set the content,

```ts
const handleCreate = React.useCallback(
		(editor: Editor) => {
			if (content && editor.isEmpty) {
				editor.commands.setContent(content);
			}
		},
		[content],
	);
```

```ts
	onCreate: ({ editor }) => handleCreate(editor),
```

While the limit is obeyed and no content is set in the above way, but by directly passing the `content` to the `useEditor` hook sets the content in the editor bypassing the limit.

I have added a [CodeSandbox](https://codesandbox.io/p/sandbox/tiptap-react-qidlsv) to reproduce this issue, please let me know if I can be of help

### Browser Used

Firefox

### Code Example URL

https://codesandbox.io/p/sandbox/tiptap-react-qidlsv

### Expected Behavior

The `content` should not be set when the `limit` is set & the size of the content is longer than the allowed limit.

### Additional Context (Optional)

_No response_

### Dependency Updates

- [X] Yes, I've updated all my dependencies.

### PR DESCRIPTION
**Pull request by gethari**
Fixes #5851

https://github.com/user-attachments/assets/48554ff9-308e-482a-a083-1164d3ffe4ef

### CODE REVIEW

**Comment by gethari** [comment]
@nperez0111 is this ok ? I have made changes as suggested, I could'nt able to run `npm run changeset` earlier as I was taking my base branch from `develop` it was showing , hence I took branch from `main`, Am i correct ?

```
Failed to find where HEAD diverged from main. Does main exist ?
```

**Comment by gethari** [comment]
Hey @nperez0111 , I think I might have caused a side effect because of this, when the charLimit is set, whenever we try to call `setContent` , its not getting reflected 😢

**Comment by nperez0111** [comment]
That doesn't sound right to me, can you reproduce in a sandbox & prove that it this.

Most likely, you are running into something a lot of people do, trying to put html in setContent and thinking it will work exactly as you input it. As a test, could you try doing insertContent which takes a different codepath than setContent

**Comment by gethari** [comment]
@nperez0111 please find the [Sanbox](https://codesandbox.io/p/sandbox/fragrant-morning-mlpffd), 

The size of the content inside `setContent` is 321, so if we set the limit >= the size, this works, but when we use limit of 300, the content is not getting overridden, I guess previously it was just setting the content all-together without obeying the limit, after my `appendTransaction`, i think this is getting skipped

**Comment by nperez0111** [comment]
Yea, not sure what is going on here & I don't have time to fix it. Could you open a new issue? What is strange to me is that it feels like appendTransaction should always run so I'm not sure that we need to run the modification in the filter transaction anymore, & just let it be in the appendTransaction instead

**Pull request merged**
