### PR TITLE
Exclude superscript from subscript, and vice versa.

### PR DESCRIPTION
**Pull request by BrianHung**

### CODE REVIEW

**Comment by philippkuehn** [comment]
ah yes. makes sense!

**Comment by hanspagel** [comment]
Throws an error when the other isn’t loaded. #1438 😅

**Comment by philippkuehn** [comment]
reverted. not sure about a workaround for now.

**Comment by umar-ahmed** [comment]
> reverted. not sure about a workaround for now.

@philippkuehn Maybe add to the docs for both plugins that the user can extend the schema to make them mutually exclusive:

```js
import Superscript from '@tiptap/extension-superscript'
import Subscript from '@tiptap/extension-subscript'

const CustomSuperscript = Superscript.extend({
  excludes: 'subscript',
})

const CustomSubscript = Subscript.extend({
  excludes: 'superscript',
})
```

That approach seems to make the least assumptions about the user's editor configuration

**Pull request merged**
