### PR TITLE
 fix(suggestion): dropdown can't be closed with `Esc` (#4380)

### PR DESCRIPTION
**Pull request by rfgamaral**
## Changes Overview
See discussion here: https://github.com/ueberdosis/tiptap/pull/4380#issuecomment-2306513901

## Implementation Approach

Suggested by @nperez0111.

## Testing Done
I checked that this works with the single room collaboration demo opened in different browsers, and manually tested all the small issues for which I recorded small videos in the commented linked above.

## Checklist
- [x] I have created a [changeset](https://github.com/changesets/changesets) for this PR if necessary.
- [x] My changes do not break the library.
- [ ] I have added tests where applicable.
- [x] I have followed the project guidelines.
- [x] I have fixed any lint issues.

### CODE REVIEW

**Review by nperez0111 — APPROVED** [review]

**Comment by nperez0111** [comment]
Appreciate your verification @rfgamaral glad it worked (that never happens 😄 )

**Comment by nperez0111** [comment]
Releasing v2.6.6 now

**Comment by Nantris** [comment]
I notice that this PR only hides the dropdown, but if the user presses `Enter` with it hidden, the suggestion will still submit. The currently exposed properties don't appear to be sufficient for end-developers to work around this themselves unless I'm overlooking something.

**Comment by Nantris** [comment]
Anyone have thoughts on how this could be addressed? Should I make a new issue for this?

**Comment by nperez0111** [comment]
New issue would be preferred over tracking here. Overall this code is a mess to maintain & would require a refactor from first principles to actually be acceptable

**Pull request merged**
