### PR TITLE
Add Video Component

### PR DESCRIPTION
**Pull request by willfranklyn**
Added a Video Component based off of the Images Component. Would love feedback on the PR as I've only recently been using tiptap. I needed a to add a video in my editor and did not see a way to do so. I hope others can utilize this component.

### CODE REVIEW

**Comment by willfranklyn** [comment]
The examples page loaded successfully after running `yarn install` and `yarn build:examples`.

**Comment by willfranklyn** [comment]
Looking to add the ability to drop a video onto the page. Might run into some issues here though since the video won't be hosted anywhere.

**Comment by hanspagel** [comment]
We updated the default branch to `main` and deleted the `master` branch, that led to the close of this PR. Sorry, that was not intended.

**Comment by hanspagel** [comment]
Thanks for your work on this extension @willfranklyn!  

We don’t plan to add new features to tiptap 1, as we fully focus on [the development of tiptap 2](https://blog.ueber.io/post/our-plan-for-tiptap-2/). (It’s gonna be amazing.) Your code looks really good to me! I added this to the list of community extensions, so others looking for it can add it to their project:
https://github.com/ueberdosis/tiptap/issues/819

That’s also a pretty good candidate for tiptap 2. We’ll consider to add it to the core. Thanks for the suggestion! 💖

**Comment by lizy0329** [comment]
> Thanks for your work on this extension @willfranklyn!
> 
> We don’t plan to add new features to tiptap 1, as we fully focus on [the development of tiptap 2](https://blog.ueber.io/post/our-plan-for-tiptap-2/). (It’s gonna be amazing.) Your code looks really good to me! I added this to the list of community extensions, so others looking for it can add it to their project:
> #819
> 
> That’s also a pretty good candidate for tiptap 2. We’ll consider to add it to the core. Thanks for the suggestion! 💖

For image/video upload, tiptap x uppy is a best idea.

**Comment by SalahAdDin** [comment]
> Thanks for your work on this extension @willfranklyn!
> 
> We don’t plan to add new features to tiptap 1, as we fully focus on [the development of tiptap 2](https://blog.ueber.io/post/our-plan-for-tiptap-2/). (It’s gonna be amazing.) Your code looks really good to me! I added this to the list of community extensions, so others looking for it can add it to their project: #819
> 
> That’s also a pretty good candidate for tiptap 2. We’ll consider to add it to the core. Thanks for the suggestion! 💖

so, you have no plans to include it in **Tiptap2**, right?

**Pull request closed without merging**
