### PR TITLE
✨ Follow Ref on ForwardRef component in reactRenderer

### PR DESCRIPTION
**Pull request by castroCrea**
- Allow us to pass Ref to a function ForwardRef component in reactRenderer (useful for mention)

### CODE REVIEW

**Comment by philippkuehn** [comment]
Hey @castroCrea, can you please explain to me what this is helpful for?

**Comment by castroCrea** [comment]
It is helpful if we use functional component `React.forwardRef` instead of class component.

For example, in Mention, you pass onKepPress to the ref but it only works for Class component. Will be nice for this to work with functional component also.

**Comment by philippkuehn** [comment]
Ah great! So this would be a fix for https://github.com/ueberdosis/tiptap/issues/1040?

Since I don’t really have experience with `forwardRef`: What would a functional component have to look like to be able to call `onKeyDown` from outside there as well?

**Comment by castroCrea** [comment]
Yes exactly

**Comment by philippkuehn** [comment]
Perfect! Thanks!

**Comment by philippkuehn** [comment]
The [mentions demo](https://www.tiptap.dev/examples/suggestions) is now using a functional component 🎉

**Pull request merged**
