### PR TITLE
Fix List issues & add support for Mod keys

### LINKED ISSUE #2747: Backspacing through a nested list doesn't work properly
### What’s the bug you are facing?

When backspacing through a list and not starting at the last item, it clears the current item and the text of it's parent... but that is about it.

Video provided

[https://www.loom.com/share/0dc205342dae40ecba2b73e715abf030](https://www.loom.com/share/0dc205342dae40ecba2b73e715abf030)

### Which browser was this experienced in? Are any special extensions installed?

Version 99.0.4844.51 (Official Build) (x86_64)

### How can we reproduce the bug on our side?

My video above demonstrates the bug.

This is done within your sandbox on tiptap.dev

### Can you provide a CodeSandbox?

_No response_

### What did you expect to happen?

I expect to naturally backspace through the list.

### Anything to add? (optional)

_No response_

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [X] Yes, I’m a sponsor. 💖

### LINKED ISSUE #3128: Confusion and frustration when dealing with empty list items (aka "Bullet List Limbo")
### What’s the bug you are facing?

Exiting lists in TipTap can be done by hitting `Enter`, which is standard behavior in all editors. But the way this editor deals with `Backspace` in an empt list item suggests that users can exit lists also using `Backspace`. The problem is that Backspace only visually removes the bullet, suggesting to the user that they are about to write a paragraph, when in fact they are still writing bullet items.

This leads to lots of unwanted formatting issues, confusion and frustrating editing experience.

### Which browser was this experienced in? Are any special extensions installed?

Safari, Version 15.6.1 (17613.3.9.1.16)
macOS, 12.5.1

### How can we reproduce the bug on our side?

I used https://tiptap.dev/examples/default and recorded the issue as well as my expected behavior here: https://www.loom.com/share/001d5b52095a4caa889db51c58a44932

This is what causes "Bullet List Limbo".
1. You need a list with at least two items, the last one being empty:

CleanShot 2022-08-26 at 18 37 57@2x

2. Place the cursor on the second item (the empty one), and hit backspace. What you get looks like this:

CleanShot 2022-08-26 at 18 38 31@2x

3. At this point, lots of users believe they have exited the bulleted list and continue as if it where a paragraph:
CleanShot 2022-08-26 at 18 39 50@2x

4. After finishing the paragraph, they hit enter and are surprised to see this:
CleanShot 2022-08-26 at 18 40 25@2x

At this stage the editing experience goes in all sorts of wrong directions, because they struggle to get the editor to do what they want it to do. In other words: the state of the editor is no more in sync with the mind of the user, causing immense frustration and believing the editor is broken.

### Can you provide a CodeSandbox?

_No response_

### What did you expect to happen?

Hitting backspace on an empty list item should completely remove the row and move the cursor to the item above. 

In this scenario...
CleanShot 2022-08-26 at 18 43 56@2x

hitting backspace should result in this:
CleanShot 2022-08-26 at 18 44 38@2x

and not this:
CleanShot 2022-08-26 at 18 44 23@2x

Explained here in the Loom, and comparing to Apple notes: https://www.loom.com/share/001d5b52095a4caa889db51c58a44932?t=141 

### Anything to add? (optional)

This behaviour might be intended, or technically correct, but it causes lots of our users to believe that the editor is broken. I assume because it breaks with their learned experience from other editors.

This issue might be small, but once a user is in this state of "Bulleted List Limbo", a lot of other issues occur with indentation and formatting, resulting in a horrendous writing experience. 

Fixing this would make our lives so much more enjoyable :-)

### Did you update your dependencies?

- [X] Yes, I’ve updated my dependencies to use the latest version of all packages.

### Are you sponsoring us?

- [x] Yes, I’m a sponsor. 💖 (on behalf of Doist, makers of Todoist and Twist)

### PR DESCRIPTION
**Pull request by bdbch**
## Please describe your changes

This PR fixes various issues with lists (for example when the cursor is placed right behind a list and backspace is pressed).

It also moves all list helpers into core so they can be used by taskLists too.

## Checklist

- [x] The changes are not breaking the editor
- [x] Added tests where possible
- [x] Followed the guidelines
- [x] Fixed linting issues

## Related Issues

closes #3128
closes #2747

### CODE REVIEW

**Comment by terlan4** [comment]
When will this version be released? I would love to see my backspace work asap 🙂❤

**Comment by bdbch** [comment]
@svenadlung could you take a look?

**Review by svenadlung — APPROVED** [review]

**Comment by Slapbox** [comment]
I was looking through these changes and I'm curious what the changes to the `cut` command accomplished? I'm curious because we're reliant on that command in our own code. Was there some `mapping`-related issue with the old implementation?

**Comment by bdbch** [comment]
If I remember correctly the issue occured when something was cut and moved after the cut content. Since the mapping wasn't respected beforehand, the insert position was invalid.

I could check again if I find some time what it was about exactly.

**Comment by Slapbox** [comment]
I also noticed the logic in these Backspace handler lines lacks corresponding logic in the Delete handler: https://github.com/ueberdosis/tiptap/blob/2a11d39fe90f1e5a1e251414f262a148a33b92ef/packages/core/src/helpers/listHelpers/handleBackspace.ts#L20-L42

**Comment by Slapbox** [comment]
> If I remember correctly the issue occured when something was cut and moved after the cut content. Since the mapping wasn't respected beforehand, the insert position was invalid.

Thanks for the reply @bdbch! I was curious looking at it because it seems related to the weird mapping misbehavior in #4283

**Pull request merged**
