### PR TITLE
allow users to pass a custom `findSuggestionMatch` to Suggestion plugin

### PR DESCRIPTION
**Pull request by estrattonbailey**
## Please describe your changes
Hey there 👋 we're using Tiptap and the Suggestions plugin to implement hashtags in our editor. Our hashtag validation is a little more complex than what the default `findSuggestionMatch` allows, so I started investigating how I could replace the matching with a custom version. This seemed to be the most straightforward approach.

Disclaimer: this might be more of a conversation starter than a fix, but fwiw it does work for my needs right now. Happy to help improve.

## How did you accomplish your changes
Just added a new property `findSuggestionMatch` to the `Suggestion` plugin, with types that match the built-in function.

## How have you tested your changes
Just manually integrating at the moment, but lmk if I can assist with a test suite.

## How can we verify your changes
I think it's straightforward.

## Checklist

- [x] The changes are not breaking the editor
- [x] Added tests where possible
- [x] Followed the guidelines
- [x] Fixed linting issues

## Related issues
N/A

### CODE REVIEW

**Review by bdbch — APPROVED** [review]
LGTM. @svenadlung ?

**Comment by svenadlung** [comment]
Looks good to me. Thank you so much for your contribution @estrattonbailey.

I think we could add the new prop to the docs as well: https://tiptap.dev/api/utilities/suggestion

Btw: I just see that the `allow` prop is not documented there either 🥲

**Comment by estrattonbailey** [comment]
Thanks for the quick review! I added to the docs, feel free to edit.

I'm not 100% on what `allow` does so I'll leave that to y'all.

**Comment by estrattonbailey** [comment]
Hey @svenadlung 👋  just wanted to bump this in case it got lost in the shuffle 😄

**Comment by svenadlung** [comment]
Awesome, thx. LGTM.

**Review by svenadlung — APPROVED** [review]

**Comment by estrattonbailey** [comment]
Hey @svenadlung 👋 no particular rush on my end, but any chance we can get this merged and released soon-ish? Thanks for your help!

**Comment by estrattonbailey** [comment]
Hey @svenadlung just bumping this again :) thanks!

**Review by janthurau — APPROVED** [review]

**Pull request merged**
