### PR TITLE
Included Typescript declarations

### PR DESCRIPTION
**Pull request by juanparati**
I include an extended version of the Typescript declaration for tiptap

I decided to submit the declarations to this project repository instead of [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) because I think is much easy to maintain.

### CODE REVIEW

**Comment by Mach12** [comment]
Thank you for this, I hope it gets merged soon. I know Tiptap 2 will be in TS but this seems to be quite a while away so typings are appreciated.

**Comment by hanspagel** [comment]
Thanks @juanparati for your work on this! You’re part of what made us consider TypeScript for tiptap 2.

BTW It’s not too far away, I just published a blog post about it. 🙃 https://blog.ueber.io/post/our-plan-for-tiptap-2/

**Comment by juanparati** [comment]
It's a pleasure to collaborate with Tiptap project. ^_^

**Comment by Mach12** [comment]
Hey can I just ask why [the Node class](https://github.com/ueberdosis/tiptap/blob/895e75856ece486a0451d7b9003dd68f00440ddf/index.d.ts#L111) and [the Mark class](https://github.com/ueberdosis/tiptap/blob/895e75856ece486a0451d7b9003dd68f00440ddf/index.d.ts#L122) are extending Prosemirror models?

I tried out your typings in my project and they seem to work for the most part, but the originals[(1)](https://github.com/ueberdosis/tiptap/blob/3b8ba27cc8871a7b8949fc423a8335edf7f9c3c8/packages/tiptap/src/Utils/Mark.js#L3)[(2)](https://github.com/ueberdosis/tiptap/blob/3b8ba27cc8871a7b8949fc423a8335edf7f9c3c8/packages/tiptap/src/Utils/Node.js#L3) both inherit Tiptap's Extension class instead... are you sure this is right?

**Comment by juanparati** [comment]
@Mach12: I think that is correct. The extension class describes the Prosemirror model.

**Pull request closed without merging**
