### PR TITLE
fix-editor-element-type

### PR DESCRIPTION
**Pull request by BrianHung**
`options.element` is the same as `place` as defined in https://prosemirror.net/docs/ref/#view.EditorView.constructor. This PR expands the type for `options.element` such that `element` can also be a callback or a `{mount: Element}`, as allowed by ProseMirror.

https://github.com/ueberdosis/tiptap/blob/43611ea2e70d3dc66ff907ba7ca377bf74814543/packages/core/src/Editor.ts#L267

This allows consumers of TipTap and React to directly pass HTML attributes to the ProseMirror dom element instead of through EditorView:

```tsx
export const EditorContent: React.FC<EditorContentProps> = memo(props => {
  const editorContentRef = useRef<HTMLDivElement>(null);
  const setEditor = useSetEditor();

  useLayoutEffect(() => {
    const element = editorContentRef.current!;
    
    // Initialize editor and mount onto editorContentRef.
    const editor = new Editor({
      // @ts-ignore
      element: {mount: element},
      ...props.editorOptions,
    });

    editor.createNodeViews();

    // Update context when editor initializes and updates.
    setEditor(editor);
    editor.on("transaction", () => setEditor(editor));

    // Cleanup editor on component unmount.
    return () => {
      editor.destroy();
    };
  }, [props.editorOptions]);

  const { editorOptions, ...rest } = props;
  return <div ref={editorContentRef} {...rest} />;
});
```

### CODE REVIEW

**Comment by bdbch** [comment]
Hey @BrianHung thanks for your PR.

The tests and linters all failed. Could you merge the current main branch and fix the linting issues so we can take a look at your solution?

**Comment by bdbch** [comment]
Seems like the build is not going through. :) If it goes through I'll take a look.

**Comment by BrianHung** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/063c09f5361fb081e09221d955c565f4c60fd0f1/types/prosemirror-view/index.d.ts#L242

https://github.com/ProseMirror/prosemirror-view/blob/427d278aaaacde422ed1f2b8c84bb53337162775/src/index.js#L46

**Comment by BrianHung** [comment]
Don't know enough typescript to know exactly why `Node<any, any>` is different from `Node`

```
Argument of type 'Node<any, any> | ((p: Node<any, any>) => void) | { mount: Node<any, any>; } | undefined' is not assignable to parameter of type 'Node | ((p: Node) => void) | { mount: Node; } | undefined'.
```

**Comment by bdbch** [comment]
It's 1am over here. I'll try to help you out tomorrow morning if you didn't figure it out by yourself then :) Maybe we can find a solution. Have a good night / day!

**Comment by bdbch** [comment]
@BrianHung did you find a way to figure it out?

**Comment by BrianHung** [comment]
Still working on it; need to remove assumptions in codebase that editor.options.element is always an HtmlElement. We can instead use editor.view.dom but test cases are not passing so have to fix those. 😅

**Comment by bdbch** [comment]
Any updates? @BrianHung

**Comment by bdbch** [comment]
ping @BrianHung any updates?

**Comment by BrianHung** [comment]
@bdbch Sorry I've been quite busy over the last few months :sweat_smile: If you can take over this PR, that'd be great.

**Comment by bdbch** [comment]
no worries. I'll look into it!

**Comment by bdbch** [comment]
I tried to resolve all issues but realized that also the React views are not working properly anymore so I'd close this PR until you have time to work on it again. Feel free to reopen when you updated it.

**Pull request closed without merging**
