### PR TITLE
Update getCurrentListItemPos.ts

### PR DESCRIPTION
**Pull request by fantasticit**
## Please describe your changes

use `@tiptap/pm` instead of `prosemirror`

## How did you accomplish your changes

.

## How have you tested your changes

.

## How can we verify your changes

.

## Remarks

[add any additional remarks here]

## Checklist

- [x ] The changes are not breaking the editor
- [x ] Added tests where possible
- [x] Followed the guidelines
- [x ] Fixed linting issues

### CODE REVIEW

**Review by svenadlung — APPROVED** [review]

**Comment by svenadlung** [comment]
@bdbch ping :)

**Review by bdbch — APPROVED** [review]

**Comment by svenadlung** [comment]
@fantasticit Could you please rebase and fix the merge conflict? 🙏

**Comment by bdbch** [comment]
We also have some linting issues in here. Would be great to have this fixed! :) Ty for the PR.

**Comment by fantasticit** [comment]
Sorry for not responding in a timely manner, I've been too busy at work lately. I noticed that the file was removed in the latest code, so I'll close this pr.

**Pull request closed without merging**
