### PR TITLE
Add TypeScript definitions (partial)

### PR DESCRIPTION
**Pull request by Intelx**
Partially complete type definitions for the common use cases of tiptap. Definitions are declared in package.json files so they can be used directly when imported as npm packages.

Note: Typings included for NodeView can be used with [vue-property-decorator](https://github.com/kaorun343/vue-property-decorator)

### CODE REVIEW

**Comment by douglance** [comment]
Can we merge or submit to @DefinitelyTyped?

**Comment by wompeter** [comment]
Please !

**Comment by grindpride** [comment]
I write some shims.dt.s using types from this PR. Thanks to @Intelx
<script src="https://gist.github.com/grindpride/bc1f9e8db202c681b6d35c1055627a42.js"></script>
<script src="https://gist.github.com/grindpride/ce8a7b7d94f8c8d797262dc278607682.js"></script>
<script src="https://gist.github.com/grindpride/e436290d359b6da878b320b8ebf33446.js"></script>

**Comment by LifeIsStrange** [comment]
@grindpride I don't understand how to use your shims until this is merged, what should be the layout of files? What should we put on tsconfig.json ?

**Comment by beasty-web** [comment]
@Intelx great job, works flawlessly on my end!

Any chance you can submit these to @DefinitelyTyped?
I don't think that they will be merged any time soon here 🙁

**Comment by mkalayci35** [comment]
+1

**Comment by hanspagel** [comment]
We updated the default branch to `main` and deleted the `master` branch, that led to the close of this PR. Sorry, that was not intended.

**Comment by hanspagel** [comment]
Thanks for your work @Intelx! Your pull request and all the people asking for TypeScript made us consider to use it for version 2 and - just so you all know - tiptap 2 will be written in TypeScript. 🎉

That said, we are already knee deep in the development of version 2 and I don’t see that we’re going to merge this here for version 1.

**Pull request closed without merging**
