### PR TITLE
chore: upgrade y-prosemirror

### PR DESCRIPTION
**Pull request by nikgraf**
## Please describe your changes

- Upgrade to the latest y-prosemirror version
- Make sure it's compatible with y-prosemirror 1 and people can choose their own version

## How did you accomplish your changes

Update the peerDependencies and devDependencies

## How have you tested your changes

Not yet

## How can we verify your changes

Make sure all collaboration demos are working as expected.

## Remarks

I guess there was a reason why it was locked to a specific y-prosemirror, but couldn't find any remarks or issues.

## Checklist

- [x] The changes are not breaking the editor
- [x] Added tests where possible
- [x] Followed the guidelines
- [x] Fixed linting issues

### CODE REVIEW

**Comment by bdbch** [comment]
Thanks @nikgraf – I think we'd have to test this more extensively to see if it introduces bugs or breaking changes.

**Comment by nikgraf** [comment]
@bdbch makes sense, do you have some protocol on how to test such changes? I could look into it

**Comment by janthurau** [comment]
Thanks for this! I'll merge this as https://github.com/ueberdosis/tiptap/pull/4638, as I had to fix a few tests which were broken on our side first.

**Comment by nikgraf** [comment]
awesome, glad to see movement here :)

**Pull request closed without merging**
