### PR TITLE
Fix undo/redo still worked with isEditable false

### PR DESCRIPTION
**Pull request by Nantris**
## Changes Overview
Block undo/redo when `editable.isEditable` isn't truthy.

## Testing Done
None

## Verification Steps
None

## Checklist
- [ ] I have created a [changeset](https://github.com/changesets/changesets) for this PR if necessary.
- [x] My changes do not break the library.
- [ ] I have added tests where applicable.
- [x] I have followed the project guidelines.
- [x] I have fixed any lint issues.

## Related Issues
#5547

### CODE REVIEW

**Comment by Nantris** [comment]
I'm not sure why this check is necessary. None of the other commands seem to need it. Something seems not right about this.

**Comment by Nantris** [comment]
I don't understand how/why this breaks building the examples. Is that unrelated to the PR? Looking at other recent PRs I think it might be,

**Comment by Nantris** [comment]
Friendly bump on this. Not sure this is the best approach, but the editor isn't production-ready with this bug present.

**Comment by nperez0111** [comment]
We tried this solution & it does not actually works @Nantris which is why we've not taken it into the project. 

prosemirror-history has default keybinds that listen for the historyUndo event: https://github.com/ProseMirror/prosemirror-history/blob/master/src/history.ts#L409-L419 which is still listening even when the editor is not editable.

So this should be fixed upstream.


I can assure you that the editor is production ready, millions use it

**Comment by Nantris** [comment]
Whoops I don't think I meant to re-open this. I agree this PR doesn't work.

**Pull request closed without merging**
