### PR TITLE
Tweak `getTextBetween` to prepend `blockSeparator` to block node even if block node doesn't have any children 

### PR DESCRIPTION
**Pull request by hivokas**
## Please describe your changes

Currently `getTextBetween` function doesn't prepend `blockSeparator` to block nodes without children.

This PR updates it to prepend `blockSeparator` to block nodes in any case (even if block node doesn't have any children).

## How did you accomplish your changes

I have tweaked the implementation to not depend on child nodes of blocks when deciding whether `blockSeparator` should be prepended. 

## How have you tested your changes

I used preview link generated by Netlify bot below.

## How can we verify your changes

Use preview link generated by Netlify bot below.

## Remarks

Below are before/after examples.

### Without empty paragraph 

```
Hello!
How are you?
```

Before: `'Hello!'+BLOCK_SEPARATOR+'How are you?'`
After: `'Hello!'+BLOCK_SEPARATOR+'How are you?'`

### With empty paragraphs

```
Hello!

How are you?
```

Before: `'Hello!'+BLOCK_SEPARATOR+'How are you?'`
After: `'Hello!'+BLOCK_SEPARATOR+BLOCK_SEPARATOR+'How are you?'` **(it's breaking change, but I consider it a bugfix)**

## Checklist

- [x] The changes are not breaking the editor
- [ ] Added tests where possible
- [x] Followed the guidelines
- [x] Fixed linting issues

## Related issues

N/A

### CODE REVIEW

**Comment by knitevision1** [comment]
@bdbch @svenadlung +1 on this one
Currently concurrent empty like breaks are not reflected in `getText()`

E.g. in the screenshot between line 2 and 5 there're're line breaks, but `getText` only returns one `\n`

Selection_414

**Comment by hivokas** [comment]
@knitevision1 if this PR gets merged, you (and I) will be able to achieve the desired result with `getText({ blockSeparator: '\n' })` (default separator is `\n\n`).

**Comment by hivokas** [comment]
@bdbch could you take a look at this PR when you get a moment? Looking at reactions in this PR, it looks like I'm not the only one who wants this change.

**Review by bdbch — APPROVED** [review]

**Comment by hivokas** [comment]
Thanks @bdbch!

**Comment by itzcull** [comment]
When will this get released? So happy with this change, has made dealing with whitespaced text content so annoying

**Comment by hivokas** [comment]
@itzcull it's released 🎉

**Pull request merged**
