### PR TITLE
feat(extensions): new hashtag extension

### PR DESCRIPTION
**Pull request by Narixius**
This PR adds hashtag support to the editor. This extension can be integrated with suggestions.

### CODE REVIEW

**Comment by bdbch** [comment]
From a first look it looks good.

https://deploy-preview-3288--tiptap-embed.netlify.app/src/marks/hashtag/react/

While testing here, I found a few bugs, specially when the hashtag gets used at the start of a line. Could you investigate this behaviour?

**Comment by piotrski** [comment]
Is there a reason why hashtag and mention do not have a common implementation? https://github.com/ueberdosis/tiptap/blob/main/packages/extension-mention/src/mention.ts

**Comment by bdbch** [comment]
After coming back to this I wonder if it's actually needed. The mentions package is doing this already for you and most of the logic is a 1:1 copy of the suggestions + mention setup just with a different suggestion char I think?

**Comment by nperez0111** [comment]
Agreed, closing

**Pull request closed without merging**
