### PR TITLE
🧹 Allow `editor.setEditable` to omit updates

### PR DESCRIPTION
**Pull request by ZaymonFC**
As per #3289

### CODE REVIEW

**Review by bdbch — APPROVED** [review]

**Comment by ZaymonFC** [comment]
@bdbch I've resolved the lint errors.

**Comment by gethari** [comment]
@bdbch we are looking forward for this to be merged as we are facing a similar problem while using the `setEditable()` API

**Comment by gethari** [comment]
@ZaymonFC looks like this PR was already approved by `Dominik`, can you try to re-run the cypress suite & see if it passes on local ? Or any way to re-run this ?

**Comment by ZaymonFC** [comment]
@gethari I can't re-run the tests since I'm not a project administrator. I can't see how this would be a breaking change so I figure the UI test suite is flakey.

**Comment by gethari** [comment]
@ZaymonFC I foresee that the `docs` for this particular API will also need to be updated [HERE](https://github.com/ueberdosis/tiptap/blob/main/docs/api/editor.md#seteditable) for this to be merged

**Comment by gethari** [comment]
@bdbch hope you guys had an amazing vacation 🏄 . Did you get a chance to check this out ? and I also have #3541 waiting for your suggestions/comments

**Comment by bdbch** [comment]
Hey! Thanks @gethari - I restarted the cypress and lint tests and will see if we can merge this today.

**Comment by gethari** [comment]
@bdbch can we get a new release with this changes please ?

**Pull request merged**
