### PR TITLE
Fix : React DND broken when used within a NodeViewWrapper

### PR DESCRIPTION
**Pull request by tej1562**
Drag event doesn't work on components wrapped inside a NodeViewWrapper.

## Please describe your changes

Currently, drag events are explicitly prevented on NodeView. This is also applied to NodeView children due to event propagation, thus preventing drag events on the components inside NodeView. This PR adds a check to ensure drag events are only prevented on the NodeView parent.

## How did you accomplish your changes

Added event target check to ensure drag prevention on NodeView doesn't propagate to child components.

```
    if (!isDraggable && isSelectable && isDragEvent && event.target === this.dom) {
      event.preventDefault()
    }

    if (isDraggable && isDragEvent && !isDragging && event.target === this.dom) {
      event.preventDefault()
      return false
    }
```

## How have you tested your changes

Created a NodeView with a react dnd component using NodeViewWrapper. Drag works as expected on the react dnd component.

## How can we verify your changes

Create a NodeView with draggable component and check if component can be dragged.

## Remarks

[add any additional remarks here]

## Checklist

- [x] The changes are not breaking the editor
- [x] Added tests where possible
- [x] Followed the guidelines
- [x] Fixed linting issues

## Related issues

#5018

### CODE REVIEW

**Comment by bdbch** [comment]
Could be that it comes from these checks:

https://github.com/ueberdosis/tiptap/blob/05ed5560215bf81726d993925e9ed39930136d3d/packages/core/src/NodeView.ts#L135-L145

not sure though - would need some test case in our demo for that.

**Comment by bdbch** [comment]
Since you check for `this.dom` - would that break something if I drag a child node of my prosemirror node that is not supposed to be draggable?

**Comment by bdbch** [comment]
Sorry, misclicked there!

Oops

**Comment by tej1562** [comment]
The drag on child node won't affect the drag behaviour of parent node. Here, `this.dom` refers to dom element representing the parent NodeView and it's drag behaviour only depends on the `draggable` property. If `draggable` is set to `false` on the NodeView, then it remains undraggable but child nodes within NodeView can still be dragged.

**Review by bdbch — APPROVED** [review]
LGTM

**Pull request merged**
