### PR TITLE
fix(extension-code-block): #3604 paste code from vscode

### PR DESCRIPTION
**Pull request by aliasliao**
**fixes https://github.com/ueberdosis/tiptap/issues/3604 , https://github.com/ueberdosis/tiptap/issues/3321**

This line (L267) causes the wrong insertion position:
https://github.com/ueberdosis/tiptap/blob/main/packages/extension-code-block/src/code-block.ts#L267
```ts
tr.setSelection(TextSelection.near(tr.doc.resolve(Math.max(0, tr.selection.from - 2))))
```

Removing L267 can fix the bug.
But I think the better solution is to replace selection with a text node, rather than imperatively inserting the copied content  : )

cc @bdbch

### CODE REVIEW

**Comment by aliasliao** [comment]
@bdbch Can you help to review this?

**Review by bdbch — APPROVED** [review]
LGTM

@svenadlung cc

**Comment by aliasliao** [comment]
@svenadlung need your review, please

**Comment by svenadlung** [comment]
@aliasliao Thank you. I'll have a look next week due to public holidays.

**Comment by svenadlung** [comment]
@aliasliao Sorry for the delay. There is a small difference in some cases. In that case the cursor after pasting is not in the code node, but in the following node. Can you please check again?

**Comment by aliasliao** [comment]
> @aliasliao Sorry for the delay. There is a small difference in some cases. In that case the cursor after pasting is not in the code node, but in the following node. Can you please check again?

@svenadlung Hi, I fixed this issue in the latest commit. Could you please review it?

There is one more case that I found hard to handle: if there is a CodeBlock after the cursor before pasting, the cursor remains inside that CodeBlock after pasting, instead of moving to the newly created code block.

**Review by nperez0111 — DISMISSED** [review]
LGTM

**Review by nperez0111 — APPROVED** [review]

**Pull request merged**
