### PR TITLE
Multiple mention chars ['@', '#',...]

### PR DESCRIPTION
**Pull request by ep1kt3t0s**
It is common in social media platforms to use `@` and `#` characters for mentions.
Implementing multiple mention characters in Tiptap.

This PR is a draft PR as I did not poke around enough to how to build and test the code.
I appreciate if someone can take over to confirm it works and make any necessary changes then we can merge to `main`.

### CODE REVIEW

**Comment by cadars** [comment]
The use of `#` might clash with the planned(?) hashtag extension that could be used for tagging: https://www.tiptap.dev/api/nodes/hashtag

**Comment by philippkuehn** [comment]
@ep1kt3t0s Do you have any example app/servive that uses both (@ & #) for the same mention functionality?

**Comment by ep1kt3t0s** [comment]
@cadars why hashtag extension is separate? It is only a mention/suggestion system with a different character.
@philippkuehn Facebook and Twitter both has @user and #topic systems. Why would we think of them as separate functionalities?
Also, Quill supports exactly the feature I tried to make with this PR: https://github.com/afry/quill-mention#example

**Comment by ep1kt3t0s** [comment]
Plus, we'd like to provide functionality to people to create more suggestion/mention characters, one might want to use `+something`  as well.

**Comment by philippkuehn** [comment]
Yeah but for that case it’s better to create multiple instances of the mention extension (or a copy of it) to create different nodes.

**Comment by ep1kt3t0s** [comment]
@philippkuehn I think I tried multiple instances but I don't think I could get it working. Does it work? I can give it another shot if so.

**Comment by ep1kt3t0s** [comment]
@philippkuehn, cannot add two Mention instances:
```
Uncaught RangeError: Adding different instances of a keyed plugin (mention$)
    at index.es.js:761
    at Array.forEach (<anonymous>)
    at new Configuration (index.es.js:759)
    at EditorState.reconfigure (index.es.js:917)
    at Editor.createView (tiptap-core.esm.js:2725)
    at new Editor (tiptap-core.esm.js:2574)
    at new Editor (tiptap-react.esm.js:28)
    at tiptap-react.esm.js:59
    at invokePassiveEffectCreate (react-dom.development.js:23487)
```

I've also found https://github.com/ueberdosis/tiptap/issues/11 but it was also not helpful.

So do you want to go ahead with this PR (after testing it) or do you have another solution to get `@` and `#` and possibly more characters like `/` and `+` working together?

**Comment by hanspagel** [comment]
Thanks for the PR, but yes, we would recommend use two instances of the Mention extension. Add a pluginKey to the configuration, like that:

pluginKey: new PluginKey('hashtag')

Red more: https://prosemirror.net/docs/ref/#state.PluginKey
See also: #1816

Thanks for your work on this! I think we’ll keep that way and just make it more clear in the docs.

**Comment by ep1kt3t0s** [comment]
@hanspagel thank you for the pointer, just tried different PluginKeys with multiple Mention instances but when an item is inserted into the editor it always gets the second `char` e.g. `@word` works but becomes `#word` after selected.
Am I missing something else I wonder? It doesn't look like both mention instances share any stateful object.

Example: https://codesandbox.io/s/tiptap-mention-plugin-multiple-mentions-wuohj?file=/src/Editor.jsx:791-2281

**Comment by philippkuehn** [comment]
Ah, you are right. There is a limitation about rendering/parsing different mention nodes because they share the same `parseHTML` and `renderHTML` methods. https://github.com/ueberdosis/tiptap/blob/73a278a5d3853e8742560939453cbd5b4d6f7ad4/packages/extension-mention/src/mention.ts#L107-L113

We could improve that by making these methods dynamic.

```js
parseHTML() {
  return [
    {
      tag: `span[data-${this.name}]`,
    },
  ]
}
// ...
```

Later we could create different extensions based on the mention extension.

```js
const UserMention = Mention
  .extend({
    name: 'user',
  })
  .configure({
    suggestion: {
      char: '@',
      pluginKey: new PluginKey('user-mention'),
    },
  })

const HashtagMention = Mention
  .extend({
    name: 'hashtag',
  })
  .configure({
    suggestion: {
      char: '#',
      pluginKey: new PluginKey('hashtag-mention'),
    },
  })
```

But I’m not sure about this change. I’ve always seen the mention extension as a user mention extension. For a hashtag node, for example, I still wanted to build it so that it doesn’t render as an atom node, but as text that changes dynamically as you type (a mention node is currently always rendered as a "block"). So maybe it’s best to create a copy of the mention extension for now. What do you think @hanspagel?

**Comment by ep1kt3t0s** [comment]
Maybe we can leave the system less opinioated and not fixed to one or two (@ and #) characters. Is there any gain having assumptions on which mention (suggestion) character correlates to users/PRs/issues/commands/topics/notes/groups/teams/channels..?

**Comment by philippkuehn** [comment]
The logic for this is in the [@tiptap/suggestion](https://github.com/ueberdosis/tiptap/tree/main/packages/suggestion) package, which you can use for any of your nodes. The [@tiptap/extension-mention](url) is only one example (probably the most common one) for using suggestions together with user mentions.

If you want to use suggestions for other things like PRs/issues/commands/topics/notes/groups/teams/channels/wikis this is fine. There is already one [experiment for using it with commands](https://www.tiptap.dev/experiments/commands).

**Comment by ep1kt3t0s** [comment]
@philippkuehn I saw that example page but I did not see an example for React.
Is there any documentation on how to use it with React?

**Pull request closed without merging**
