### PR TITLE
docs: Adding first draft of JSDocs

### PR DESCRIPTION
**Pull request by bdbch**
## Please describe your changes

This PR adds tons of JSDocs for almost all Tiptap extensions excluding the rendering extensions (React, Vue 2 and Vue 3).

This is a draft for now until I feel happy about the amount of jsdocs and will make this PR ready for review as soon as I think we can throw the first batch of jsdocs out there.

### CODE REVIEW

**Comment by bdbch** [comment]
@svenadlung this would be ready for review for now. I think the next batch of js docs can come in isolated from this.

**Comment by bdbch** [comment]
@svenadlung could we take a look at this as soon as possible? I spent a bit of time into this and don't want it to draft to far out of sync with the current branch. :)

**Review by svenadlung — DISMISSED** [review]
Sorry for the delay. Great work!

**Comment by nperez0111** [comment]
Fantastic PR here, really helpful!

**Pull request merged**
