### PR TITLE
Remove `element.current` from `useEffect` in `BubbleMenu` and `FloatingMenu`

### PR DESCRIPTION
**Pull request by ValentaTomas**
Changes to the `element.current` don't trigger `useEffect` rerender and shouldn't be used in the dependency array.
One discussion about this is for example here: https://stackoverflow.com/questions/60476155/is-it-safe-to-use-ref-current-as-useeffects-dependency-when-ref-points-to-a-dom

It's also causing some subtle bugs when mounting and unmounting editors.

### CODE REVIEW

**Comment by philippkuehn** [comment]
Hey, in this [PR](https://github.com/ueberdosis/tiptap/pull/2018/files) you added also a check for `element.current`. Can this also be removed then?

And could you do the same change to the `FloatingMenu` too please?

**Comment by ValentaTomas** [comment]
Oh thanks, I completely forgot about the `FloatingMenu`.

I will also fix the `element.current` issue properly!

**Comment by ValentaTomas** [comment]
This should be it.

I have some problems with "build / lint (16) (pull_request) Failing after 1m" -- there is an error in the "Commit fixed linting errors" check. @philippkuehn any idea?


```
error: pathspec 'patch-1' did not match any file(s) known to git
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Comment by ValentaTomas** [comment]
Please don't merge it yet, I'm still testing some behavior.

**Comment by ValentaTomas** [comment]
Ok, `BubbleMenu` looks ok, but I have not tested `FloatingMenu`. It think it should be ok, but I really don't want to break anything. Do you have automated tests or some sandbox where you test  the features?

**Comment by hanspagel** [comment]
Thanks!

The linting check is broken, but if it would pass you wouldn’t see an exception. You could probably run yarn lint locally to see if there’s something off.

(yarn run lint:fix can help fixing linting issues, but not for all rules)

**Comment by ValentaTomas** [comment]
`lint:fix` helped - it was just bad formatting.

When I have the `FloatingMenu` tested I will notify you here.

**Comment by ValentaTomas** [comment]
`FloatingMenu` seems ok too. I think the PR is ready to merge.

**Comment by philippkuehn** [comment]
looks good. thanks!

**Comment by hanspagel** [comment]
Thanks for your work! 👏

**Comment by ValentaTomas** [comment]
No problem. Thank you for creating TipTap.

**Pull request merged**
